global:
  scrape_interval: 15s

scrape_configs:
  - job_name: telegram-bot
    static_configs:
      - targets: ['telegram-bot:8000']

  - job_name: postgres_exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: redis_exporter
    static_configs:
      - targets: ['redis-exporter:9121']
