"""Fix orders address and phone migration

Revision ID: 1f41acf4d0b8
Revises: a90cd76f5409
Create Date: 2025-03-20 19:44:05.468743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f41acf4d0b8'
down_revision: Union[str, None] = 'a90cd76f5409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
