"""Add model Category (created_at) row

Revision ID: 40076bfd508e
Revises: 42e4ff5592e1
Create Date: 2025-03-28 15:11:00.036093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40076bfd508e'
down_revision: Union[str, None] = '42e4ff5592e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
