"""remove address and phone columns

Revision ID: 42e4ff5592e1
Revises: 1f41acf4d0b8
Create Date: 2025-03-20 19:55:15.642629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e4ff5592e1'
down_revision: Union[str, None] = '1f41acf4d0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'address')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
