"""Initial migration

Revision ID: a90cd76f5409
Revises: 
Create Date: 2025-03-20 19:16:26.444727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90cd76f5409'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_cart_product', 'cart', ['product_id'], unique=False)
    op.create_index('idx_cart_user', 'cart', ['user_id'], unique=False)
    op.create_index('idx_category_name', 'category', ['name'], unique=True)

    # Обновляем данные для orders
    op.execute("UPDATE orders SET address = 'Не указан' WHERE address IS NULL")
    op.execute("UPDATE orders SET phone = '+79990000000' WHERE phone IS NULL")

    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)

    # Обновляем данные для user
    op.execute("UPDATE \"user\" SET first_name = 'Не указано' WHERE first_name IS NULL")  # <-- Кавычки для user
    op.execute("UPDATE \"user\" SET last_name = 'Не указано' WHERE last_name IS NULL")
    op.execute("UPDATE \"user\" SET phone = '+79990000000' WHERE phone IS NULL")
    op.execute("UPDATE \"user\" SET address = 'Не указан' WHERE address IS NULL")

    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index('idx_category_name', table_name='category')
    op.drop_index('idx_cart_user', table_name='cart')
    op.drop_index('idx_cart_product', table_name='cart')
    # ### end Alembic commands ###