"""add username to user

Revision ID: e37eca1e968c
Revises: 2ae957656909
Create Date: 2025-06-22 14:53:46.970627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37eca1e968c'
down_revision: Union[str, None] = '2ae957656909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.alter_column('user', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Telegram User ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_user_id_seq'::regclass)"))
    op.create_index(op.f('ix_user_username'), 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'user_id',
               existing_type=sa.BIGINT(),
               comment='Telegram User ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_user_id_seq'::regclass)"))
    op.drop_column('user', 'username')
    op.alter_column('order_item', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
